import {Inter} from "next/font/google";
import "./globals.css";
import Navbar from "@/app/components/layout/Navbar";
import Footer from "@/app/components/layout/Footer";

const inter = Inter({subsets: ["latin"]});

export const metadata = {
    title: "Blog App",
    description: "Generated by create next app",
};


export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <Navbar/>
        <div className="m-auto w-[60%]">
            {children}
        </div>
        <Footer/>
        </body>
        </html>
    );
}
